eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-login.apps.us-east-1.starter.openshift-online.com/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: provider-service
  
management:
  security:
    enabled: false

logging:
  level:
    com.eureka.provider: DEBUG